### ISSUE TITLE
This project has a meaningful contribution to society

### ISSUE THREAD

**Issue by szoech** [jakeSteinburger/SpecOS#6]
We are in dire and immediate need of innovation in the OS and wider Software Development platform space and this project does not aim to improve status quo.

However, working on it is probably a lot of fun + it contributes to the developers experience in said field and as they are a member of society, it thereby also contributes to society.

Hi reddit

**Comment by Goldside543** [comment]
I opened a pull request.

Am I thus making a contribution to a contribution to society?

If someone makes a contribution to my contribution, are they contributing to a contribution to a contribution to society?

How long can this endless contribution chain go?

**Comment by UnmappedStack** [comment]
Heya, thanks for the mood brightening issue :D

I'm going to have to close this still though, as it isn't technically on topic, but thank you none the less.

**Comment by V3ntus** [comment]
Keep at it Jake! Love your work

**Comment by UnmappedStack** [comment]
> I opened a pull request.
> 
> Am I thus making a contribution to a contribution to society?
> 
> If someone makes a contribution to my contribution, are they contributing to a contribution to a contribution to society?
> 
> How long can this endless contribution chain go?

Everybody knows readme typo fixes are the biggest contribution to society you can make xD

**Comment by maximus-sallam** [comment]
IDK, does society even read anymore?

**Comment by zanxz-lol** [comment]
Clearly, you have no meaningful contribution to society! :D

Have a good day, and remember to post real issues on the repo! :)

**Comment by UnmappedStack** [comment]
> Clearly, you have no meaningful contribution to society! :D
> 
> Have a good day, and remember to post real issues on the repo! :)

I think you may have shared this in the wrong issue btw, the original one is in a different thread, I believe this one is a parody :D but thanks for your kind support

**Comment by zanxz-lol** [comment]
ah i feel stupid lol

**Comment by ar1ja** [comment]
hi

**Comment by zanxz-lol** [comment]
hi

**Comment by fstendel** [comment]
After all, that guys issue made a lot of people laugh pretty hard.

Keep up the good work Jake!
