### ISSUE TITLE
Move pml4, GDT and IDT to the bitmap heap

### ISSUE THREAD

**Issue by Dcraftbg** [jakeSteinburger/SpecOS#7]
Move the pml4, GDT and IDT to the bitmap heap. Having them as global variables makes the elf file unnecessarily bigger and makes it so limine has to allocate more continuous physical memory for your kernel. They take up 1 page of memory anyway so there's no sort of optimization in keeping them as global variables (besides allocation cost which is negligible since the bitmap allocator should find a page really quickly).

**Comment by UnmappedStack** [comment]
Done :D Here's the commit hash with the change: e1e9b66d3f4af82e019aab6955c5672952b8bad0
